# Generated by Django 4.2.7 on 2023-12-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_delete_document_notes_docfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='docfile',
        ),
    ]
