# Generated by Django 4.2.7 on 2023-12-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_document_remove_notes_docfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
