# Generated by Django 4.2.7 on 2023-12-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
    ]
